### ISSUE TITLE
Return classification failure

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/macaw#295]
I'm seeing the following when disassembling some code compiled from AWS-LC:

```
# 0x7603d8 repz ret
  r407 := read_mem rsp_0 (bvle8)
  r408 := (bv_add rsp_0 (0x8 :: [64]))
  # 0x7603d8: {rip => r407;rsp => r408}
  classify failure
    { rip = r407
    , rax = r10_0
    , rsp = r408
    , df = false
    , x87top = 0x7 :: [3]
    }
    Branch: IP is not an mux:
    let r407 := read_mem rsp_0 (bvle8)
     in r407
    no return call: Noreturn target r407 is not a valid address.
    Call classifer failed.
    Return: Pattern match failure in do expression at src/Data/Macaw/Discovery/Classifier.hs:282:5-18
    Jump: Jump value r407 is not a valid address.
    Jump table: Absolute jump table: Pattern match failure in do expression at src/Data/Macaw/Discovery/Classifier/JumpTable.hs:268:3-21
    Jump table: Relative jump table: Unaligned IP not a mem offset: r407
    PLT stub: Pattern match failure in do expression at src/Data/Macaw/Discovery/Classifier/PLT.hs:121:5-18
    Tail call: Not a stack offset
```

A standard `ret` from the assembly source has been translated into `repz ret`, which I gather is an optimization that `gcc` will insert sometimes (CF https://repzret.org/p/repzret/) apparently to work around limitations in the branch predictors of early X86_64 implementations.

So, I suppose we should enhance the return classifier to recognize this pattern.

I'm confused, though... this code is currently being reasoned about as part of the SAW CI suite, so I don't understand why this isn't causing problems already.  Is this classification failure somehow benign in a way I don't understand?

**Comment by travitch** [comment]
I think that the `repz ret` probably isn't at fault - macaw is okay with it. It is probably the case that the return classifier failed to fire for another reason (some other code before that). Can you provide some context before that?

**Comment by robdockins** [comment]
Here is the Macaw dump for the function in question
[dump.txt](https://github.com/GaloisInc/macaw/files/8980010/dump.txt)

**Comment by robdockins** [comment]
The call to `_aesni_ctr32_ghash_6x` might not be ABI-compliant... maybe that is confusing it?

**Comment by travitch** [comment]
The way macaw relies on the ABI is a bit odd - it assumes that callee-save registers are not clobbered (i.e., their values are preserved after the call). The possible failure mode is that if this code relies on a normally caller-save register remaining untouched, that would mean that macaw's abstract interpretation pessimistically clobbers some abstract state that it would later need

**Comment by robdockins** [comment]
OK, mystery solved. In the original context where this occurs, we are specifically telling Macaw to treat `rax` as a preserved register. In that context, the code discovery succeeds.
