### ISSUE TITLE
Error parsing system symbol: Identifier must start with a letter.

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/macaw#6]
Function `x86RegName` in module `Data.Macaw.X86.Symbolic` calls `What4.Symbol.systemSymbol` on a bunch of strings that begin with "!", such as "!ip".

https://github.com/GaloisInc/macaw/blob/6a29ed6e56d1114055fe015cae7abd8b538aab91/x86_symbolic/src/Data/Macaw/X86/Symbolic.hs#L105

However, function `systemSymbol` requires its input to start with a letter (the "!" must occur somewhere in the string, but not at the start) as explained in the source. Otherwise it calls `error`.

https://github.com/GaloisInc/crucible/blob/2db0648fe0c7485071f992fb4a79600789134f9b/what4/src/What4/Symbol.hs#L82

The invalid symbol names in `Data.Macaw.X86.Symbolic` cause the test suite for package macaw-x86-symbolic to fail with calls to `error`.

**Comment by travitch** [comment]
It looks like this has been fixed at some point
