### ISSUE TITLE
breakages in non-Travis CI built code

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/macaw#82]
Several of the packages in this repo appear to no longer build (e.g., macaw-ppc, macaw-arm, etc) and are not currently directly being built by any CI. Perhaps we would benefit from adding macaw and all its packages of interest to fryingpan?

**Comment by pnwamk** [comment]
FYI, currently the only packages being built on Travis are the following (i.e., those listed in the stack yaml files):
```
- base
- symbolic
# X86 specific repos
- x86
- x86/support
- x86_symbolic
```

**Comment by joehendrix** [comment]
I don't think those packages built when I created the Travis file either (or at least they didn't build without warnings), and so I haven't made them part of the Travis process.

I'm OK with trying to get them building, and adding them to the travis file when they do.  I don't want to turn off "-Werror" in the Travis yaml file to do so though because keeping the library warning free is important to me, and that's been the only way I know to keep a library warning free when people merge commits.

**Comment by pnwamk** [comment]
As a side note/contextual FYI for the build errors (for whomever pokes at this first), it seems the first error encountered is regarding a missing type parameter for `AbsProcessorState`:

```
src/Data/Macaw/PPC/Eval.hs:46:28: error:
    • Expecting one more argument to ‘AbsProcessorState (PPCReg ppc)’
      Expected a type, but
      ‘AbsProcessorState (PPCReg ppc)’ has kind
      ‘* -> *’
    • In the type signature:
        postPPCTermStmtAbsState :: (ppc ~ SP.AnyPPC var,
                                    PPCArchConstraints var) =>
                                   (forall tp. PPCReg ppc tp -> Bool)
                                   -> Memory (RegAddrWidth (ArchReg ppc))
                                      -> AbsProcessorState (PPCReg ppc)
                                         -> RegState (PPCReg ppc) (Value ppc ids)
                                            -> PPCTermStmt ppc ids
                                               -> Maybe (MemSegmentOff (RegAddrWidth (ArchReg ppc)),
                                                         AbsBlockState (PPCReg ppc))
   |
46 |                         -> AbsProcessorState (PPCReg ppc)
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Macaw/PPC/Eval.hs:162:21: error:
    • Expecting one more argument to ‘AbsProcessorState (ArchReg ppc)’
      Expected a type, but
      ‘AbsProcessorState (ArchReg ppc)’ has kind
      ‘* -> *’
    • In the type signature:
        postCallAbsState :: (ppc ~ SP.AnyPPC var,
                             PPCArchConstraints var) =>
                            proxy ppc
                            -> AbsProcessorState (ArchReg ppc)
                               -> RegState (ArchReg ppc) (Value ppc ids)
                                  -> ArchSegmentOff ppc -> AbsBlockState (ArchReg ppc)
    |
162 |                  -> AbsProcessorState (ArchReg ppc)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I toyed with what seemed like the straightforward fix for those and started getting errors about records w/ missing fields (which was when I stopped digging for now), e.g.:

```
src/Data/Macaw/PPC/Eval.hs:56:28: error:
    • Constructor ‘CallParams’ does not have the required strict field(s): stackGrowsDown
    • In the expression:
        CallParams
          {MA.postCallStackDelta = 0, MA.preserveReg = preservePred}
      In an equation for ‘params’:
          params
            = CallParams
                {MA.postCallStackDelta = 0, MA.preserveReg = preservePred}
      In the expression:
        do let params = ...
           Just (nextIP, absEvalCall params s0 regState nextIP)
   |
56 |               let params = MA.CallParams { MA.postCallStackDelta = 0
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

```

Also, FYI for any future interested parties, these breakages are currently visible on frying pan under `sfe`'s `master.HEAD` builds (i.e., job sfe:master.HEADs-ghc844:macaw-ppc).

**Comment by joehendrix** [comment]
I'm going to close this as we've migrated to Github actions and I think the PPC code builds now.

**Comment by travitch** [comment]
The follow up is #175 to get PowerPC under CI, but yes we can close this one
