### ISSUE TITLE
macaw-ppc is broken after some recent macaw-base changes

### ISSUE THREAD

**Issue by travitch** [GaloisInc/macaw#83]
Tracking down all of the issues currently at play.  So far:
- Additional type parameters to `AbsProcessorState`
- `mkInitialRegsForBlock` and `postCallAbsState` has been removed from `ArchitectureInfo`
- The type of `postArchTermStmtAbsState` has changed
- New functions in `ArchitectureInfo`: `extractBlockPrecond`, `initialBlockRegs`, and `archCallParams`

**Comment by travitch** [comment]
@joehendrix question: `postArchTermStmtAbsState` returns a `IntraJumpTarget`.  That includes a `InitJumpBounds`.  Is that meant to just be passed-through the return value? What changes might need to be made in the `InitJumpBounds`?

**Comment by travitch** [comment]
Ah, I was somewhat mistaken - the return value of `postArchTermStmt` contains an `InitJumpBounds` instead of a `IntraJumpBounds` - what sorts of constraints are there on the returned jump bounds/how might one construct those?

**Comment by joehendrix** [comment]
It should represent constraints on what we can infer on the next state after the terminal statement returns to the next instruction.  For x86 system calls, I use `postCallBounds`.

The information is used for jump tables primarily in Macaw, but that also needs to track aliasing between registers and when a register or stack location points to an offset of the stack.
